server:
  servlet:
    context-path:


spring:
  redis:
    host: 127.0.0.1 # Redis服务器地址
    database: 0 # Redis数据库索引（默认为0）
    port: 6379 # Redis服务器连接端口
    password: # Redis服务器连接密码（默认为空）
    timeout: 1000ms # 连接超时时间
    maxTotal: 100
    maxIdle: 90



mybatis-plus:
  configuration:
    # 关闭驼峰命名规则
    map-underscore-to-camel-case: false


mail:
#  host: smtp.qq.com
#  username: 1758855483@qq.com
#  password: ysccvlzzjtwzbjgg
  properties.mail.smtp.auth: true
  properties.mail.smtp.starttls.enable: true
  properties.mail.smtp.starttls.required: true